# Generated by Django 2.1.5 on 2019-02-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=22, max_digits=25)),
                ('y', models.DecimalField(decimal_places=22, max_digits=25)),
                ('z', models.DecimalField(decimal_places=22, max_digits=25)),
                ('t', models.DecimalField(decimal_places=3, max_digits=13)),
            ],
        ),
    ]
